### ISSUE TITLE
Validate more interactive features (completion, etc)

### ISSUE THREAD

**Issue by nrbgt** [gt-coar/jupyterlab-gt-coar-theme#7]
Users report hard-to-read text in completions. Do a pass through all the LSP/JKM features to verify contrast.

**Comment by nrbgt** [comment]
![Screenshot from 2021-02-19 11-30-23](https://user-images.githubusercontent.com/7581399/108532471-e1e53f80-72a5-11eb-9de7-58285e8330a1.png)

**Comment by sanbales** [comment]
Wonder if you could programmatically run through the possible combinations of foreground and background colors and make sure the contrast is `>4.5`.

https://stackoverflow.com/questions/9733288/how-to-programmatically-calculate-the-contrast-ratio-between-two-colors

**Comment by nrbgt** [comment]
PRs welcome!

if imma do that, it's going to be like https://github.com/pydata/pydata-sphinx-theme/pull/294 and fix lab core first.
